### ISSUE TITLE
combine two api url to one output

### ISSUE THREAD

**Issue by jaman7** [axios/axios#2316]
I am trying to combine two api json url, adding to the first key and add objects from the second api url.
the problem is that with *console.log(JSON.stringify(todosWithTasks))*, there is no content in the *task key*. On the other hand, in the usual *console.log(todosWithTasks)* it looks like everything is fine, in the *task key* there are objects.
so by trying to map the *task* key in *react* I do not get the object keys in the rendered component. If I download the modified json file in axios, it's everything ok, in *console.log (JSON.stringify (todosWithTasks))* it's fine

**Example Code**
```js
async componentDidMount() {
    this.isLoading = true;
    await axios
        .get('/sets')
        .then(async response => {
            let tempTodos = response.data;
            tempTodos.forEach(todo => (todo.task = []));
            let todosWithTasks = tempTodos.map(todo => {
                let tasks = [];
                axios
                    .get('/sets/' + todo.id + '/tasks')
                    .then(response2 => {
                        todo.task = response2.data;
                        return todo;
                    })
                    .catch(error => {
                        console.log(error);
                    });
                return todo;
            });
            console.log(todosWithTasks);
            console.log(JSON.stringify(todosWithTasks));
            this.todos = todosWithTasks;
        })
        .catch(error => {
            console.log(error);
        });
}
```
**json from first api url**
```
[
    {
        "id": 1,
        "name": "list1",
        "description": "description1"
    }
]
```
**json second api url**
```
[
    {
        "id": 1,
        "name": "task1",
        "description": "description task1"
    }
]
```
**this is trying to get**
```
[
    {
        "id": 1,
        "name": "list1",
        "description": "description1",
        "task": [
            {
                "id": 1,
                "name": "task1",
                "description": "description task1"
            },
        ]
    }
]
```
that is what I got in the console
**output from console.log(JSON.stringify(todosWithTasks))**
```
[{"id":1,"name":"list1","description":"description1","task":[]}]
```
**output from console.log(todosWithTasks)** looks fine
```
(1) [{…}]
    0:
        description: "description1"
        id: 1
        name: "list1"
        task: Array(1)
            0: {id: 1, name: "task1", description: "description task1"}
            length: 1
            __proto__: Array(0)
        __proto__: Object
    length: 1
    __proto__: Array(0)
```
