### ISSUE TITLE
Axios calls between docker containers

### ISSUE THREAD

**Issue by jimlundblad** [axios/axios#2817]
I'm having issues with docker and axios, my docker containers are:
wordpress and nginx reverse proxy, and a express.js app,

but when axios is trying to call /wp-json from the wordpress or nginx container it get's ECONNREFUSED and resolves 127.0.0.1 instead of the container IP

**The error**
```javascript
{
  Error: connect ECONNREFUSED 127.0.0.1:443
  at TCPConnectWrap.afterConnect[as oncomplete](net.js: 1107: 14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443,
  config: {
    url: 'http://wordpress:80/multisite/wp-json/wp/v2/pages',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [
      [Function: transformRequest]
    ],
    transformResponse: [
      [Function: transformResponse]
    ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    domain: null,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: null,
      hostname: 'wordpress.local',
      port: null,
      nativeProtocols: [Object],
      pathname: '/',
      search: null,
      slashes: true,
      host: 'wordpress.local',
      hash: null,
      query: null,
      href: 'https://wordpress.local/'
    },
    _redirectCount: 1,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET / HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.2\r\nHost: wordpress.local\r\nConnection: close\r\n\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      timeout: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/',
      _ended: false,
      res: null,
      aborted: undefined,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Circular],
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object]
    },
    _currentUrl: 'https://wordpress.local/',
    _isRedirect: true
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}
```
**the server**
```nginx
worker_processes 1;

events { worker_connections 1024; }

http {

    sendfile on;

    upstream docker-nodejs {
        server nodejs:8080;
    }

    upstream docker-apache {
        server wordpress:80;
    }

    server {
        listen      80;
        server_name wordpress.local localhost;

        location / {
            rewrite ^ https://$host$request_uri? redirect;
        }
    }

    server {
        listen      443           ssl;
        server_name               wordpress.local localhost;

        root /var/www/html/web;
        index index.php;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ssl_certificate           /etc/certs/wordpress.local.crt;
        ssl_certificate_key       /etc/certs/wordpress.local.key;

        include /etc/nginx/redirects.conf;

        proxy_redirect off;                                                       
        proxy_buffering off;                                                      
        proxy_set_header Host $host;                                              
        proxy_set_header X-Real-IP $remote_addr;                                  
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            proxy_pass         http://docker-apache;
        }
        location /nodejs {
            proxy_pass         http://docker-nodejs;
        }
    }
}
```

** docker**
```
version: "2.1"
services:

  nginx:
      image: nginx:latest
      restart: always
      volumes:
        - ./logs/nginx:/var/log/nginx
        - ./:/var/www/html:rw,cached
        - ./certs/:/etc/certs
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./assets/nginxredirects.conf.erb:/etc/nginx/redirects.conf
      ports : 
        - "80:80" 
        - "443:443"
      networks:
        fairr-docker-network:

```yml
  wordpress:
    image: wordpress
    container_name: "wordpress"
    restart: always
    volumes:
      - ./:/var/www/html
    links:
      - mariadb:mysql
    networks:
        fairr-docker-network:
          ipv4_address: 172.20.0.212

  nodejs:
    image: node:10
    container_name: "nodejs"
    volumes:
      - ./docker/nodejs:/usr/src/service/node_modules
      - ./nodejs:/usr/src/service      
    working_dir: /usr/src/service
    command: bash -c "yarn start"
    environment:
      - REDIS=redis://redis
      - MONGO=mongodb://mongo:27017/collection
    depends_on:
      - mongo
      - redis
      - wordpress
    ports:
      - 8080:8080
    networks:
        fairr-docker-network:
          ipv4_address: 172.20.0.199

networks:
  fairr-docker-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```
